nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmScopes:
  "flashport-org":
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"


